const fieldServiceProjectionFull = {
  referenceDate: 1,
  referenceYear: 1,
  referenceMonth: 1,
  deliveryDate: 1,
  videos: 1,
  returnVisits: 1,
  studies: 1,
  books: 1,
  brochures: 1,
  magazines: 1,
  weblinks: 1,
  campaignTracts: 1,
  tracts: 1,
  cards: 1,
  otherpublications: 1,
  hours: 1,
  hoursBetel: 1,
  creditHours: 1,
  minutes: 1,
  notes: 1,
  placements: 1,
  pioneerId: 1,
  publisherId: 1,
  congregationId: 1,
};

const fieldServiceProjectionBasics = {
  referenceDate: 1,
  deliveryDate: 1,
  videos: 1,
  returnVisits: 1,
  studies: 1,
  hours: 1,
  hoursBetel: 1,
  creditHours: 1,
  minutes: 1,
  notes: 1,
  placements: 1,
  // pioneerId: 1,
  // publisherId: 1,
  // congregationId: 1,
};

module.exports = { fieldServiceProjectionFull, fieldServiceProjectionBasics };
