const publisherProjectionFull = {
  baptized: 1,
  birthDate: 1,
  baptismDate: 1,
  householder: 1,
  congregationalPrivilege: 1,
  id: 1,
  firstName: 1,
  middleName: 1,
  lastName: 1,
  fullName: 1,
  gender: 1,
  address: 1,
  phones: 1,
  email: 1,
  elderDate: 1,
  servantDate: 1,
  inactivityDate: 1,
  reactivationDate: 1,
  firstFieldService: 1,
  notes: 1,
  startPioneer: 1,
  statusService: 1,
  statusAssociation: 1,
  servicePrivilege: 1,
  pioneerNumber: 1,
  profile: 1,
  userId: 1,
  congregationId: 1,
  createdAt: 1,
  updatedAt: 1,
  modifiedBy: 1,
  __v: 1,
};

const publisherProjectionBasic = {
  id: 1,
  firstName: 1,
  middleName: 1,
  lastName: 1,
  gender: 1,
  phones: 1,
  email: 1,
  modifiedBy: 1,
};

module.exports = { publisherProjectionFull, publisherProjectionBasic };
